In [17]:
from datasets import load_dataset

In [24]:
dataset = load_dataset("squad_kor_v1")

Downloading builder script: 100%|██████████| 4.76k/4.76k [00:00<00:00, 16.7MB/s]
Downloading metadata: 100%|██████████| 2.39k/2.39k [00:00<00:00, 24.9MB/s]
Downloading readme: 100%|██████████| 6.12k/6.12k [00:00<00:00, 43.1MB/s]
Downloading data: 38.5MB [00:00, 79.7MB/s]/2 [00:00<?, ?it/s]
Downloading data: 3.88MB [00:00, 48.2MB/s]                  1.23it/s]
Downloading data files: 100%|██████████| 2/2 [00:01<00:00,  1.23it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 1954.93it/s]
Generating train split: 100%|██████████| 60407/60407 [00:02<00:00, 21367.14 examples/s]
Generating validation split: 100%|██████████| 5774/5774 [00:00<00:00, 25388.23 examples/s]

In [25]:
import pandas as pd

dataset['train']

Dataset({
    features: ['id', 'title', 'context', 'question', 'answers'],
    num_rows: 60407
})

In [36]:
df_train = pd.DataFrame(dataset['train'])

In [37]:
df_train

,id,title,context,question,answers
0,6566495-0-0,파우스트_서곡,1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로...,바그너는 괴테의 파우스트를 읽고 무엇을 쓰고자 했는가?,"{'text': ['교향곡'], 'answer_start': [54]}"
1,6566495-0-1,파우스트_서곡,1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로...,바그너는 교향곡 작곡을 어디까지 쓴 뒤에 중단했는가?,"{'text': ['1악장'], 'answer_start': [421]}"
2,6566495-0-2,파우스트_서곡,1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로...,바그너가 파우스트 서곡을 쓸 때 어떤 곡의 영향을 받았는가?,"{'text': ['베토벤의 교향곡 9번'], 'answer_start': [194]}"
3,6566518-0-0,파우스트_서곡,1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로...,1839년 바그너가 교향곡의 소재로 쓰려고 했던 책은?,"{'text': ['파우스트'], 'answer_start': [15]}"
4,6566518-0-1,파우스트_서곡,1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로...,파우스트 서곡의 라단조 조성이 영향을 받은 베토벤의 곡은?,"{'text': ['합창교향곡'], 'answer_start': [354]}"
...,...,...,...,...,...
60402,6467478-1-1,뉴델리_메탈로-베타락타마제,"유전자의 이름은 인도의 수도 뉴델리의 이름을 따 붙여졌는데, 이는 2009년 용 (...",뉴델리 메탈로 베타락마제가 처음 감염 된 지역은 어디인가?,"{'text': ['인도'], 'answer_start': [73]}"
60403,6467478-2-0,뉴델리_메탈로-베타락타마제,"2010년 8월, 저널 The Lancet Infectious Diseases에 최...",균은 유전자를 균에게 전달 할 수있는데 이러한 현상을 나타낸 용어는 무엇인가?,"{'text': ['유전자 전달'], 'answer_start': [253]}"
60404,6467478-2-1,뉴델리_메탈로-베타락타마제,"2010년 8월, 저널 The Lancet Infectious Diseases에 최...",박테리아가 NDM-1 유전자를 가지고 있을때 발생하는 전파를 분석하기위해 사용된 영...,"{'text': ['37건'], 'answer_start': [129]}"
60405,6490801-2-0,뉴델리_메탈로-베타락타마제,"2010년 8월, 저널 The Lancet Infectious Diseases에 최...",NDM-1 유전자를 가진 박테리아가 감수성을 보인 폴리믹슨 계열 항생제는?,"{'text': ['콜리스틴'], 'answer_start': [404]}"
60406,6490801-2-1,뉴델리_메탈로-베타락타마제,"2010년 8월, 저널 The Lancet Infectious Diseases에 최...","2010년 8월, NDM-1 유전자를 가진 박테리아의 발생과 전파를 분석한 다국적 ...","{'text': ['The Lancet Infectious Diseases'], '..."

In [39]:
cnt=0
for i in range(len(df_train['answers'])):
    if len(df_train['answers'].iloc[i]['text']) != 1:
        cnt+=1
        continue
    df_train['answers'].iloc[i] = df_train['answers'].iloc[i]['text'][0]
print(f'number of rows which contains more than 1 answers: {cnt}')

0

In [42]:
df_train = df_train[['context', 'question', 'answers']]

In [44]:
df_train.to_csv('./data/korquad_1.0/train.csv')

In [46]:
df_test = pd.DataFrame(dataset['validation'])

In [47]:
df_test

,id,title,context,question,answers
0,6548850-0-0,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배 된 날은?,"{'text': ['1989년 2월 15일'], 'answer_start': [0]}"
1,6548850-0-1,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,1989년 6월 30일 평양축전에 대표로 파견 된 인물은?,"{'text': ['임수경'], 'answer_start': [125]}"
2,6548853-0-0,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배된 연도는?,"{'text': ['1989년'], 'answer_start': [0]}"
3,6548853-0-1,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석을 검거한 장소는 경희대 내 어디인가?,"{'text': ['학생회관 건물 계단'], 'answer_start': [365]}"
4,6548853-0-2,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 조사를 받은 뒤 인계된 곳은 어딘가?,"{'text': ['서울지방경찰청 공안분실'], 'answer_start': [457]}"
...,...,...,...,...,...
5769,6511152-4-0,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생한 년도는?,"{'text': ['2016년'], 'answer_start': [0]}"
5770,6511152-4-1,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 S7엣지를 만든 회사는?,"{'text': ['삼성전자'], 'answer_start': [83]}"
5771,6511152-4-2,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년 9월 4일 갤럭시 S7엣지가 폭발한 사건이 발생한 지역은?,"{'text': ['중동 지역'], 'answer_start': [12]}"
5772,6535617-4-0,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 노트 7은 출시 며칠만에 기기 결함으로 터지기 시작하였나?,"{'text': ['18일'], 'answer_start': [286]}"
5773,6535617-4-1,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년에 갤럭시 S7 엣지가 폭발한 사건은 어느 지역에서 일어났는가?,"{'text': ['중동 지역'], 'answer_start': [12]}"

In [48]:
cnt=0
for i in range(len(df_test['answers'])):
    if len(df_test['answers'].iloc[i]['text']) != 1:
        cnt+=1
        continue
    df_test['answers'].iloc[i] = df_test['answers'].iloc[i]['text'][0]
print(f'number of rows which contains more than 1 answers: {cnt}')

number of rows which contains more than 1 answers: 0

In [49]:
df_test

,id,title,context,question,answers
0,6548850-0-0,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배 된 날은?,1989년 2월 15일
1,6548850-0-1,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,1989년 6월 30일 평양축전에 대표로 파견 된 인물은?,임수경
2,6548853-0-0,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배된 연도는?,1989년
3,6548853-0-1,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석을 검거한 장소는 경희대 내 어디인가?,학생회관 건물 계단
4,6548853-0-2,임종석,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 조사를 받은 뒤 인계된 곳은 어딘가?,서울지방경찰청 공안분실
...,...,...,...,...,...
5769,6511152-4-0,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생한 년도는?,2016년
5770,6511152-4-1,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 S7엣지를 만든 회사는?,삼성전자
5771,6511152-4-2,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년 9월 4일 갤럭시 S7엣지가 폭발한 사건이 발생한 지역은?,중동 지역
5772,6535617-4-0,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 노트 7은 출시 며칠만에 기기 결함으로 터지기 시작하였나?,18일
5773,6535617-4-1,삼성_갤럭시_S7_엣지,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년에 갤럭시 S7 엣지가 폭발한 사건은 어느 지역에서 일어났는가?,중동 지역

In [50]:
df_test = df_test[['context', 'question', 'answers']]
df_test

,context,question,answers
0,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배 된 날은?,1989년 2월 15일
1,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,1989년 6월 30일 평양축전에 대표로 파견 된 인물은?,임수경
2,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 여의도 농민 폭력 시위를 주도한 혐의로 지명수배된 연도는?,1989년
3,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석을 검거한 장소는 경희대 내 어디인가?,학생회관 건물 계단
4,1989년 2월 15일 여의도 농민 폭력 시위를 주도한 혐의(폭력행위등처벌에관한법률...,임종석이 조사를 받은 뒤 인계된 곳은 어딘가?,서울지방경찰청 공안분실
...,...,...,...
5769,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생한 년도는?,2016년
5770,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 S7엣지를 만든 회사는?,삼성전자
5771,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년 9월 4일 갤럭시 S7엣지가 폭발한 사건이 발생한 지역은?,중동 지역
5772,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,갤럭시 노트 7은 출시 며칠만에 기기 결함으로 터지기 시작하였나?,18일
5773,2016년 9월 4일 중동 지역에서 갤럭시 S7 엣지가 폭발하는 사건이 발생했다. ...,2016년에 갤럭시 S7 엣지가 폭발한 사건은 어느 지역에서 일어났는가?,중동 지역

In [51]:
df_test.to_csv('./data/korquad_1.0/test.csv')